### ISSUE TITLE
What will happen, when the user has multiple CRN number?

### ISSUE THREAD

**Issue by sushil173** [bipin0x01/meroshare-bot#10]
If the user has multiple CRN, at that time there will be multiple bank lists on the '/asba' URL.

**Comment by sushil173** [comment]
<img width="1680" alt="Screen Shot 2022-06-16 at 7 04 44 AM" src="https://user-images.githubusercontent.com/28952198/174066868-2815fa1a-5fdc-4d35-af50-06d36749a44f.png">

**Comment by bipin0x01** [comment]
Thanks , I have updated with the feature. Can you please test it once and let me know if it's working?

**Comment by bipin0x01** [comment]
https://github.com/bipin0x01/meroshare-bot/releases/tag/v0.0.3
