### ISSUE TITLE
freezes after showing Number of Accounts detected:2

### ISSUE THREAD

**Issue by tamangbadrirch** [bipin0x01/meroshare-bot#23]
Doesn't goes ahead after Number of accounts detected:
Freezes after showing message: Number of accounts detected: 1

note: has 2 dp's. tried with both but not worked.

**Comment by tamangbadrirch** [comment]
By multiple dp's i mean multiple CRN numbers of different dp's because of
C-ASBA charge, many people have multiple CRN's. So, As by default
no-account is selected, we have to choose one, i have tried with both but
problem is still same.

Please, refer the image below and revert back if any.

Thanks.

**Comment by bipin0x01** [comment]
As far as I know, the dp id and password remains the same i.e the one you get when you first register for demat at your bank. 
   For banks with multiple accounts link, you will get to choose among the existing linked bank accounts.
   If you're good , can you record the video when the error is getting occured and mail me at bt.kaji@gmail.com

**Comment by tamangbadrirch** [comment]
I have multiple banks linked with meroshare account but it doesn't give the
option to select the bank account and freezes after showing number of
accounts: 1
and cursor blinks blinks blinks no further option

**Comment by pushparajbhatta** [comment]
I am facing the same issue. I have normal meroshare accounts, no multiple banks or demats linked but it is freezing on "Number of Accounts detected".

**Comment by bipin0x01** [comment]
I request you guys all to create an new issue with all the information that might help me to fix it ASAP.
This may include an screenshot of the terminal.

Before creating an issue please be sure to check if your 'demats.txt' file is in compliance with the example used in the github Readme as well as check if the credentials you entered are correct.
