### ISSUE TITLE
'IPO list out of index' shows after detecting the accounts.

### ISSUE THREAD

**Issue by Manish1-del** [bipin0x01/meroshare-bot#24]
Everything is working but. it did not load the list of IPOs and direct jump to the part where i have select for the option.it go well upto " no of account detection" part. What is the issue here?
![Untitled](https://user-images.githubusercontent.com/109086314/178280087-05a66c65-756e-4e35-ae4d-b951989217a4.jpg)

**Comment by bipin0x01** [comment]
Sorry for the delay, Can you please update me on this on. Is the error still occurring?

**Comment by bipin0x01** [comment]
Make sure to try after downloading the latest version from https://github.com/bipin0x01/meroshare-bot.git

**Comment by bipin0x01** [comment]
Seems to be working fine. Please look at the format of the account details in demats.txt file.
