### ISSUE TITLE
"Share has been applied successfully." message is displayed after skipping one item

### ISSUE THREAD

**Issue by anandmainali** [bipin0x01/meroshare-bot#25]
<img width="565" alt="Screen Shot 2022-07-11 at 9 25 29 PM" src="https://user-images.githubusercontent.com/34227482/178304589-91f87825-239c-4d08-9214-420d5ff198f6.png">

Success message is not display after each item when applying for bluk IPO. Its only showing "IPO selected successfully".

**Comment by bipin0x01** [comment]
Sometimes due to slow network and response from the server. The message is not able to be catched by the bot, hence not showing the message. There's nothing to worry about unless any red colored error shows up.
